---
name: Feature Request
description: Suggest an idea for this project
about: Suggest an idea for this project
title: "feat: "
labels: ["feature"]
assignees: ""

body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What component of the project are you running?
      options:
        - idpscim
        - idpscimcli

  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**
        Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
